python main.py advection \
    --tag advect3D_ex2 \
    --dim 3 \
    --vis_dim 2 \
    --init_cond example2 \
    --num_hidden_layers 3 \
    --hidden_features 256 \
    -sr 50 \
    -vr 50 \
    --dt 0.05 \
    -T 240 \
    --lr 1e-4 \
    -g 1