python main.py advection \
    --tag advect4D_ex1 \
    --dim 4 \
    --vis_dim 2 \
    --init_cond example2 \
    --num_hidden_layers 3 \
    --hidden_features 256 \
    -sr 20 \
    -vr 20 \
    --dt 0.05 \
    -T 240 \
    --lr 1e-4 \
    -g 1