python main.py advection \
    --tag advect3D_ex1 \
    --dim 3 \
    --init_cond example1 \
    --num_hidden_layers 2 \
    --hidden_features 20 \
    -sr 50 \
    -vr 50 \
    --dt 0.05 \
    -T 240 \
    -g 0