python main.py \
    --exp_name elasticity2D_fall_ext_only4 \
    --num_hidden_layers 3 \
    --hidden_features 256 \
    -sr 100 \
    -vr 5 \
    --t_range 4.0 \
    -g 1 \
    --max_n_iter 10000 \
    --early_stop \
    --lr 1e-4 \
    --gravity_g ' -1.0' \
    --vis_frequency 1000