python main.py \
    --exp_name elasticity2D_fall_arap_test3 \
    --num_hidden_layers 3 \
    --hidden_features 68 \
    -sr 100 \
    -vr 5 \
    --t_range 4.0 \
    -g 2 \
    --max_n_iter 100000 \
    --early_stop \
    --lr 2e-4 \
    --gravity_g ' -0.5' \
    --ratio_collision 0e2 \
    --ratio_arap 1e-1 \
    --ratio_volume 0e0 \
    --ratio_main 1e-1 \
    --plane_height ' -3.0' \
    --vis_frequency 1000