python main.py \
    --exp_name elasticity2D_fall_ext_only9 \
    --num_hidden_layers 3 \
    --hidden_features 512 \
    -sr 100 \
    -vr 5 \
    --t_range 2.0 \
    -g 1 \
    --max_n_iter 10000 \
    --early_stop \
    --lr 1e-4 \
    --gravity_g ' -1.0' \
    --ratio_arap 0e-9 \
    --ratio_volume 0e-3 \
    --density 1e0 \
    --lambda_main 1e-2 \
    --lambda_bound 1e2 \
    --vis_frequency 1000
